server:
  port: 34525
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/syncrock_be
    data-username: postgres
    data-password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
debug: false

