# 服务器端口
server:
  port: 34525
# Spring配制项
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/syncrock_be
    data-username: postgres
    data-password: postgres
  # jpa配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
  # thymeleaf配置
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  # Redis配置项
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: 15000
      max-idle: 8
      min-idle: 0
    timeout: 0
debug: false

